# Generated by Django 4.1.4 on 2022-12-12 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calltype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dbcalltype', models.CharField(choices=[('Complain', 'Complain'), ('Assistance', 'Assistance'), ('Queries', 'Queries'), ('No response', 'No response')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('dbmsisdn', models.CharField(max_length=15)),
                ('dbname', models.CharField(max_length=100)),
                ('dboccupation', models.CharField(max_length=100)),
                ('dbdate', models.DateField()),
                ('dbdescription', models.TextField()),
                ('dbcalltype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.calltype')),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
