# Generated by Django 4.1.4 on 2022-12-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dbcalltype',
        ),
    ]
